version: '3.9'

services:
  blogit:
    image: ghcr.io/nekoluka/sakuracloud-blogit
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/nekoluka/sakuracloud-blogit:main
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./demo:/app
